apiVersion: apps/v1
kind: Deployment
metadata:
  name: rancher-demo-primary
  labels:
    app: rancher-demo-primary
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rancher-demo-primary
  template:
    metadata:
      labels:
        app: rancher-demo-primary
    spec:
      containers:
      - name: rancher-demo-primary
        image: monachus/rancher-demo
        ports:
        - containerPort: 8080
        env:
        - name: COW_COLOR
          value: red
